### ISSUE TITLE
Other users cannot drag volume slider in C menu

### ISSUE THREAD

**Issue by NullLikesNothing** [Grocel/3D-Stream-Radio#11]
The owner of a stream radio can change the volume with the C menu while other people cannot change it.
Other players should be able to change the volume for the stream radio in the C menu because some models do not have screens attached to them, and the owner of the radio can disable input which doesn't allow people to change the volume.
Some people may not like the music that is being played, and cannot lower the volume or stop the song from playing and they want to hear other radios, which the above makes it so they are unable to change the volume.

I suggest making it so people can change the volume via the C menu because the stream radio already has a menu for it.
(Image below shows a stream radio without a screen and the C menu for that radio)

![image](https://user-images.githubusercontent.com/82908498/208939749-124f0608-3cd3-4442-abb7-ef5219e2e724.png)

**Comment by Grocel** [comment]
Thanks for your feedback.

1. This is (or would be) the wrong place to change it. This slider changes the volume for all players. This menu changes serverwide/networked parameters. This is not subject to change.
2. This slider and all the other elements are protected by prop protection logic. This can not be changed. This menu behavior is actually part of Garry's mod and not of the addon.
3. Changing the volume on display changes it for all players. (also protected by prop protection logic, but for `+use` in this case)
4. You can adjust the client side volume of all radios in the settings panel (not the toolgun nor the c-menu) of the addon.
5. Changing volume or muting individual radios for your own client without affecting others is not possible at the moment.

It would need a separate control element and a separate toolgun. It would be tricky to add and will take some time. I'm not sure if this would be possible, because the toolgun could not be able to access the radio when prop protection is on. This would still be triggered, because the toolgun runs server side only.

Such a feature has not be asked for yet. Is actually quite complex to reliably and usefully implement. So I'm not sure if this is gonna make it any time soon.

**Comment by Grocel** [comment]
I made some progress on this issue. There will be dedicated options for the client (the player) to change the volume of individual radios for themselves. Update is likely to hit later this week.

![c-property-menu](https://i.imgur.com/oqR9YIY.png)
![c-right-click](https://i.imgur.com/73YFkfq.png)

**Comment by Grocel** [comment]
Fixed with eabc71f73ebe7dc37e17ab1b7f18c12affb4c621. If you have any issues with this, please let me now.
