### ISSUE TITLE
stack overflow

### ISSUE THREAD

**Issue by gmZynx** [Grocel/3D-Stream-Radio#16]
```
[3D Stream Radio] stack overflow
  1. istable - [C]:-1
   2. __newindex - lua/streamradio_core/classes/base_listener.lua:442
    3. callback - lua/streamradio_core/classes/stream.lua:182
     4. __newindex - lua/streamradio_core/classes/base_listener.lua:459
      5. callback - lua/streamradio_core/classes/stream.lua:182
       6. __newindex - lua/streamradio_core/classes/base_listener.lua:459
        7. callback - lua/streamradio_core/classes/stream.lua:182
         8. __newindex - lua/streamradio_core/classes/base_listener.lua:459
          9. callback - lua/streamradio_core/classes/stream.lua:182
           10. __newindex - lua/streamradio_core/classes/base_listener.lua:459
            11. callback - lua/streamradio_core/classes/stream.lua:182
             12. __newindex - lua/streamradio_core/classes/base_listener.lua:459
              13. callback - lua/streamradio_core/classes/stream.lua:182
               14. __newindex - lua/streamradio_core/classes/base_listener.lua:459
                15. callback - lua/streamradio_core/classes/stream.lua:182
                 16. __newindex - lua/streamradio_core/classes/base_listener.lua:459
```

**Comment by Grocel** [comment]
When did this happen? Can you reproduce the error? Do you have an addon that edits the istable function?

**Comment by gmZynx** [comment]
istable is not modified in any way

this could probably count as an addon conflict, because the only way i know how to reproduce it is with [LVS](https://steamcommunity.com/sharedfiles/filedetails/?id=2912816023)
entering a LVS vehicle with mousesteering disabled seems to cause it, but having mousesteering enabled fixes it

**Comment by Grocel** [comment]
This is interesting. Does this error happen on the client or on the server? Does it happen with every LVS vehicle? Did you notice other errors or unexpected behaviors?

I asked about the istable function, being changed, because the error seems to originate from the istable call inside the listener meta object. This kind of error can only happen if istable does changes to the table it is checking. How did you verify that it is unmodified?

However it could also be something totally different, maybe a unexpected call of an internal function from the outside or something. It could also be an interaction with a third yet unknown addon that causes both addon to break.

There is s quite remarkable things I noticed about LVS. The git repo has quite a lot of [issues](https://github.com/Blu-x92/lvs_base/issues?q=is%3Aissue+is%3Aclosed) marked as "addon conflict", "wont fix" and/or "user error". Apparently most of all issues were closed without them being fixed. This doesn't exactly look like a well maintained addon to be honest.

I will definitely take a look at this and see what I can do.

**Comment by gmZynx** [comment]
it happens clientside only
debug.getinfo says istable source is from [C]
seems to happen with every LVS vehicle

**Comment by Grocel** [comment]
Thanks for the information.

I have tested it. I was not able to reproduce the error. I tested with the latest workshop versions of LVS and symphys vehicles.  The mousesteering settings had no effect for me, I tested both settings. Radio was spawned and playing. I aimed at it, nothing happened. I tried to use the radio from outside and inside the vehicle, nothing happened.

What version are you using of LVS and the radio addon? Does this error also happen in single player / listen server? Hopefully `istable` wasn't replaced by another C function by accident or something.

**Comment by gmZynx** [comment]
i am using latest LVS version from workshop
error doesnt occur in singleplayer or listen server

the idea of a third mystery addon interfering could be true
since the error seems to only happen on the server i get the error from
ill try out addons until something breaks

**Comment by Grocel** [comment]
This is good to know. Trying out addons is a good idea. It would be interesting to know what you have found.

**Comment by gmZynx** [comment]
unfortunately i was never able to find the addon so i just went to using LFS instead of LVS, something i shouldve mentioned before is that entering the LVS vehicle makes your game lag very bad and messes with your camera view, turning stream radios off didnt fix this so i guess its an LVS issue
